### ISSUE TITLE
(BUG) UI++ dont show correctly the feature "time to possible construction with trade"

### ISSUE THREAD

**Issue by d4n13lus** [eswak/chrome-ogame-ui-extension#106]
**The extension dont show correctly the feature "time to possible construction with trade" in the construction page**. It should appear like this screenshot:

https://github.com/eswak/chrome-ogame-ui-extension/blob/master/uipp.3.png

But i cant see this two lines, only the amortization / rentable line:
https://postimg.org/image/3x48k4j7n/

i think my options are fine:
https://postimg.org/image/4mn0whz6r/

what can i do? thanks

**Comment by eswak** [comment]
oops yes I had to remove this feature in order to pass the gameforge staff's review. Any indication of "time before being able to build" is prohibited because it imitates a feature available when you're commander. Therefore I just display the missing resources (metal/cristal) in numbers...
I should upload an updated screenshot.

**Comment by d4n13lus** [comment]
@eswak thanks for the clarification
