### ISSUE TITLE
Missing resources feature and time to build doubts

### ISSUE THREAD

**Issue by scionny** [eswak/chrome-ogame-ui-extension#112]
Hi, I'm having some trouble to understand how some features work.

For instance, some times I see the missing time to build something, and some times I see the exact amount of materials needed to build it.

![image](https://user-images.githubusercontent.com/4479659/36061704-658c7506-0e5e-11e8-89e3-58fb0c7458fd.png)

I haven't found any way to configure this, I'd like to know the time left to build something if I don't have the resources yet. Is there a way to configure it?

Also, I don't understand the ship resources toggle:

![image](https://user-images.githubusercontent.com/4479659/36061714-95f197a8-0e5e-11e8-9490-647c9ea6fe6b.png)

How does it work exactly? Does it mean the ship gives prefference to the selected resources when you attack? I can't find any guide.

Thanks a lot for your time and this excellent tool. I don't need any other extensions with this one.

Great work!

**Comment by cmartinezledo** [comment]
Hi @scionny 

- We used to have that in the past, but GF did not allow it (Missing time) because it was a premium feature (OGame Commanders) so to keep OGame UI Extension allowed, @eswak had to remove that.

- That toggle, what it basically does is to calculate the number of ships required to transport the selected resources on your current planet or moon.

   - I think that what you are looking for is kinda a more useful tool for attacks. I personally like [UniverseView Extension](https://universeview.be/) as it tells me in the espionages reports, the amount of SC or LC needed for capturing the resources, as you can see in the following picture


![image](https://user-images.githubusercontent.com/10406699/36463469-f25a9d62-16a8-11e8-843d-26d474b67ce8.png)

Best!
Charlie

**Comment by scionny** [comment]
Ohh I see, thanks for the detailed answer!!
